import { ApprovableAgreement } from "./types";

export const approvableAgreements: ApprovableAgreement[] = [
  {
    id: "AGR-003",
    title: "Vendor NDA — Marketing Analytics",
    type: "Non-Disclosure Agreement",
    counterparty: "DataSense Analytics",
    submittedBy: "Dilini Jayasuriya",
    reviewedBy: "Senior Reviewer",
    submittedDate: "2026-01-20",
    reviewedDate: "2026-01-26",
    value: "N/A",
    valueNumeric: 0,
    status: "Awaiting Final Approval",
    dueDate: "2026-02-28",
    riskLevel: "Low",
    description:
      "Mutual NDA for engagement with marketing analytics vendor covering customer behavioural data. All confidentiality clauses have been reviewed and amended as required.",
    reviewerComment:
      "Definition of Confidential Information updated in Clause 1. All standard NDA clauses are acceptable. Cleared for final approval.",
    history: [
      { date: "2026-01-20", action: "Submitted", by: "Dilini Jayasuriya" },
      { date: "2026-01-25", action: "Under Review", by: "Senior Reviewer", note: "Clause 1 flagged for revision." },
      { date: "2026-01-26", action: "Reviewed — Cleared", by: "Senior Reviewer", note: "Revision accepted. Forwarded for final approval." },
    ],
  },
  {
    id: "AGR-004",
    title: "Tower Site Lease — Kandy Region",
    type: "Lease Agreement",
    counterparty: "Lanka Land Holdings",
    submittedBy: "Kasun Wickramasinghe",
    reviewedBy: "Senior Reviewer",
    submittedDate: "2026-01-15",
    reviewedDate: "2026-01-22",
    value: "LKR 1.8M",
    valueNumeric: 1800000,
    status: "Finally Approved",
    dueDate: "2026-02-15",
    riskLevel: "Low",
    description:
      "5-year lease for two tower sites in Kandy district with renewal option. Renewal clause (Clause 9) amended to specify 60-day notice period.",
    reviewerComment:
      "Renewal clause revised and accepted. No further concerns. Recommended for final sign-off.",
    approvedDate: "2026-01-25",
    history: [
      { date: "2026-01-15", action: "Submitted", by: "Kasun Wickramasinghe" },
      { date: "2026-01-20", action: "Under Review", by: "Senior Reviewer" },
      { date: "2026-01-22", action: "Reviewed — Cleared", by: "Senior Reviewer", note: "Clause 9 amendment accepted." },
      { date: "2026-01-25", action: "Finally Approved", by: "CLO", note: "Approved for execution." },
    ],
  },
  {
    id: "AGR-008",
    title: "Network Equipment Supply Agreement",
    type: "Vendor Contract",
    counterparty: "TechSupply Ltd.",
    submittedBy: "Amara Perera",
    reviewedBy: "Senior Reviewer",
    submittedDate: "2026-02-01",
    reviewedDate: "2026-02-17",
    value: "LKR 8.5M",
    valueNumeric: 8500000,
    status: "Awaiting Final Approval",
    dueDate: "2026-03-01",
    riskLevel: "High",
    description:
      "Supply agreement for network switching equipment across 12 regional hubs. Includes 3-year warranty and SLA for replacement. High value contract — CLO sign-off mandatory per procurement policy.",
    reviewerComment:
      "All key clauses reviewed. Penalty clause (Clause 8) strengthened to include liquidated damages. Warranty terms acceptable. No outstanding concerns.",
    history: [
      { date: "2026-02-01", action: "Submitted", by: "Amara Perera" },
      { date: "2026-02-10", action: "Under Review", by: "Senior Reviewer" },
      { date: "2026-02-15", action: "Clause 8 revision requested", by: "Senior Reviewer", note: "Liquidated damages clause added." },
      { date: "2026-02-17", action: "Reviewed — Cleared", by: "Senior Reviewer", note: "All revisions accepted. Escalated to CLO." },
    ],
  },
  {
    id: "AGR-009",
    title: "IT Managed Services Partnership",
    type: "Partnership Agreement",
    counterparty: "Nexus IT Solutions",
    submittedBy: "Amara Perera",
    reviewedBy: "Senior Reviewer",
    submittedDate: "2026-02-10",
    reviewedDate: "2026-02-19",
    value: "LKR 12.0M",
    valueNumeric: 12000000,
    status: "Awaiting Final Approval",
    dueDate: "2026-03-10",
    riskLevel: "Critical",
    description:
      "3-year managed services partnership covering help desk, infrastructure monitoring, and cybersecurity response. Highest-value partnership agreement this quarter — requires CLO and Board notification upon approval.",
    reviewerComment:
      "SLA schedules reviewed and tightened. Exit clause (Clause 14) now includes a 90-day wind-down provision. Liability cap set at 24 months of fees. Recommended for final approval.",
    history: [
      { date: "2026-02-10", action: "Submitted", by: "Amara Perera" },
      { date: "2026-02-13", action: "Under Review", by: "Senior Reviewer" },
      { date: "2026-02-17", action: "Multiple clause revisions requested", by: "Senior Reviewer" },
      { date: "2026-02-19", action: "Reviewed — Cleared", by: "Senior Reviewer", note: "All revisions accepted. Escalated as Critical." },
    ],
  },
  {
    id: "AGR-010",
    title: "Data Centre Colocation SLA",
    type: "Service Level Agreement",
    counterparty: "CloudHost Lanka Pvt Ltd.",
    submittedBy: "Roshan Fernando",
    reviewedBy: "Senior Reviewer",
    submittedDate: "2026-02-05",
    reviewedDate: "2026-02-20",
    value: "LKR 4.2M",
    valueNumeric: 4200000,
    status: "Returned for Revision",
    dueDate: "2026-02-28",
    riskLevel: "Medium",
    description:
      "SLA for colocation of primary data centre servers with 99.99% uptime guarantee. Returned as the force majeure clause was found insufficient for Mobitel's operational continuity requirements.",
    reviewerComment:
      "Uptime penalty sliding scale is acceptable. However force majeure clause (Clause 11) is too broad and may release the vendor from obligations during planned maintenance. Requires renegotiation.",
    history: [
      { date: "2026-02-05", action: "Submitted", by: "Roshan Fernando" },
      { date: "2026-02-10", action: "Under Review", by: "Senior Reviewer", note: "Uptime clause flagged." },
      { date: "2026-02-20", action: "Reviewed — Cleared", by: "Senior Reviewer" },
      { date: "2026-02-21", action: "Returned for Revision", by: "CLO", note: "Force majeure clause insufficient. Renegotiate Clause 11." },
    ],
  },
  {
    id: "AGR-011",
    title: "Senior Engineer Employment Contract",
    type: "Employment Contract",
    counterparty: "Internal — HR",
    submittedBy: "Dilini Jayasuriya",
    reviewedBy: "Senior Reviewer",
    submittedDate: "2026-02-12",
    reviewedDate: "2026-02-20",
    value: "N/A",
    valueNumeric: 0,
    status: "Finally Approved",
    dueDate: "2026-02-26",
    riskLevel: "Low",
    description:
      "Standard employment contract for a Senior Network Engineer. IP assignment clause narrowed to work-related inventions only. Hybrid work arrangement terms included.",
    reviewerComment:
      "IP clause revised and acceptable. All standard employment terms present. Cleared for signature.",
    approvedDate: "2026-02-21",
    history: [
      { date: "2026-02-12", action: "Submitted", by: "Dilini Jayasuriya" },
      { date: "2026-02-14", action: "Under Review", by: "Senior Reviewer", note: "IP clause flagged." },
      { date: "2026-02-20", action: "Reviewed — Cleared", by: "Senior Reviewer", note: "IP clause revision accepted." },
      { date: "2026-02-21", action: "Finally Approved", by: "CLO", note: "Approved for execution and filing." },
    ],
  },
];
