import { Agreement } from "./types";

export const agreements: Agreement[] = [
  {
    id: "AGR-001",
    title: "Network Equipment Supply Agreement",
    type: "Vendor Contract",
    counterparty: "TechSupply Ltd.",
    submittedBy: "Amara Perera",
    submittedDate: "2026-02-01",
    value: "LKR 8.5M",
    status: "Pending Review",
    dueDate: "2026-03-01",
    description:
      "Supply agreement for network switching equipment across 12 regional hubs. Includes 3-year warranty and SLA for replacement.",
    comments: [],
  },
  {
    id: "AGR-002",
    title: "Data Centre Colocation SLA",
    type: "Service Level Agreement",
    counterparty: "CloudHost Lanka Pvt Ltd.",
    submittedBy: "Roshan Fernando",
    submittedDate: "2026-02-05",
    value: "LKR 4.2M",
    status: "Under Review",
    dueDate: "2026-02-28",
    description:
      "SLA for colocation of primary data centre servers with 99.99% uptime guarantee and dedicated support tier.",
    comments: [
      {
        id: "CMT-001",
        author: "Reviewer",
        date: "2026-02-10",
        text: "Clause 4.2 on uptime penalties needs clarification — the sliding scale should be explicitly stated.",
        clause: "Clause 4.2",
      },
    ],
  },
  {
    id: "AGR-003",
    title: "Vendor NDA — Marketing Analytics",
    type: "Non-Disclosure Agreement",
    counterparty: "DataSense Analytics",
    submittedBy: "Dilini Jayasuriya",
    submittedDate: "2026-01-20",
    value: "N/A",
    status: "Reviewed",
    dueDate: "2026-02-20",
    description:
      "Mutual NDA for engagement with marketing analytics vendor covering customer behavioural data.",
    comments: [
      {
        id: "CMT-002",
        author: "Reviewer",
        date: "2026-01-25",
        text: "Definition of 'Confidential Information' in Clause 1 should explicitly exclude publicly available data.",
        clause: "Clause 1",
      },
      {
        id: "CMT-003",
        author: "Reviewer",
        date: "2026-01-26",
        text: "Reviewed and cleared after revision. No further action needed.",
      },
    ],
    reviewedDate: "2026-01-26",
  },
  {
    id: "AGR-004",
    title: "Tower Site Lease — Kandy Region",
    type: "Lease Agreement",
    counterparty: "Lanka Land Holdings",
    submittedBy: "Kasun Wickramasinghe",
    submittedDate: "2026-01-15",
    value: "LKR 1.8M",
    status: "Approved",
    dueDate: "2026-02-15",
    description:
      "5-year lease agreement for two tower sites in Kandy district. Includes option to renew for 3 additional years.",
    comments: [
      {
        id: "CMT-004",
        author: "Reviewer",
        date: "2026-01-20",
        text: "Renewal clause (Clause 9) should define the notice period more explicitly. Requested amendment.",
        clause: "Clause 9",
      },
      {
        id: "CMT-005",
        author: "Reviewer",
        date: "2026-01-22",
        text: "Amendment received and accepted. Document approved for signature.",
      },
    ],
    reviewedDate: "2026-01-22",
  },
  {
    id: "AGR-005",
    title: "IT Managed Services Partnership",
    type: "Partnership Agreement",
    counterparty: "Nexus IT Solutions",
    submittedBy: "Amara Perera",
    submittedDate: "2026-02-10",
    value: "LKR 12.0M",
    status: "Pending Review",
    dueDate: "2026-03-10",
    description:
      "3-year managed services partnership covering help desk, infrastructure monitoring, and cybersecurity response.",
    comments: [],
  },
  {
    id: "AGR-006",
    title: "Senior Engineer Employment Contract",
    type: "Employment Contract",
    counterparty: "Internal — HR",
    submittedBy: "Dilini Jayasuriya",
    submittedDate: "2026-02-12",
    value: "N/A",
    status: "Under Review",
    dueDate: "2026-02-26",
    description:
      "Standard employment contract for a Senior Network Engineer position. Non-standard clauses include IP assignment and hybrid work arrangement.",
    comments: [
      {
        id: "CMT-006",
        author: "Reviewer",
        date: "2026-02-14",
        text: "IP assignment clause (Clause 7) is broader than standard — recommend limiting to work-related inventions only.",
        clause: "Clause 7",
      },
    ],
  },
  {
    id: "AGR-007",
    title: "Roaming Agreement — MTN Africa",
    type: "Service Level Agreement",
    counterparty: "MTN Group Ltd.",
    submittedBy: "Roshan Fernando",
    submittedDate: "2026-01-28",
    value: "LKR 22.0M",
    status: "Rejected",
    dueDate: "2026-02-10",
    description:
      "International roaming agreement for voice and data services across MTN-operated networks in 10 African countries.",
    comments: [
      {
        id: "CMT-007",
        author: "Reviewer",
        date: "2026-02-03",
        text: "Revenue share model in Schedule B is not acceptable per our current international pricing policy. Rejected pending renegotiation.",
        clause: "Schedule B",
      },
    ],
    reviewedDate: "2026-02-03",
  },
];
